<a href="https://colab.research.google.com/github/Dipta04/Deep-Learning/blob/main/Module_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Device name {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")

GPU is available
Device name Tesla T4


Creating Tensors

In [3]:
a = torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
type(a)

torch.Tensor

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(2,3)

tensor([[0.7693, 0.7926, 0.6380],
        [0.3537, 0.0451, 0.5390]])

In [8]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
torch.tensor( [ [1,2,3], [4,5,6] ] )

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
torch.arange(0,10,1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
torch.linspace(1,10,10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

tensors Shape

In [13]:
x = torch.tensor( [ [1,2,3], [4,5,6] ] )
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[521167224,         0,         0],
        [      113, 603341472, 603571360]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
torch.rand_like(x, dtype = torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

Data Types

In [19]:
x.dtype

torch.int64

In [20]:
torch.tensor( [1.0,2.0,3.0,4.0], dtype=torch.int32)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [21]:
torch.tensor( [1.0,2.0,3.0,4.0], dtype=torch.float32)

tensor([1., 2., 3., 4.])

In [22]:
x = x.to(torch.float32)

In [23]:
x.dtype

torch.float32

## Mathematical Operations

Scaler Operation

In [24]:
x = torch.tensor( [ [1,2,3], [4,5,6] ] )
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [25]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [26]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [27]:
x*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [28]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [29]:
#floor
x = x * 100

In [30]:
x // 3

tensor([[ 33,  66, 100],
        [133, 166, 200]])

In [31]:
x**2

tensor([[ 10000,  40000,  90000],
        [160000, 250000, 360000]])

In [32]:
x%2

tensor([[0, 0, 0],
        [0, 0, 0]])

Element wise operation

In [33]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [34]:
a+b

tensor([[0.9357, 1.0899, 0.5967],
        [1.7253, 1.5526, 1.7335]])

In [35]:
a-b

tensor([[ 0.4879,  0.4852,  0.2399],
        [ 0.0776,  0.4411, -0.2205]])

In [36]:
a*b

tensor([[0.1594, 0.2381, 0.0746],
        [0.7426, 0.5540, 0.7391]])

In [37]:
a/b

tensor([[3.1790, 2.6049, 2.3445],
        [1.0942, 1.7938, 0.7743]])

In [38]:
a**b

tensor([[0.9267, 0.9303, 0.8560],
        [0.9180, 0.9983, 0.7614]])

In [39]:
a%b

tensor([[0.0401, 0.1829, 0.0615],
        [0.0776, 0.4411, 0.7565]])

In [40]:
c = torch.tensor( [-1,-2,-3,-4] )

In [41]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [42]:
c = torch.tensor( [1,2,3,4] )

In [43]:
torch.neg(c)

tensor([-1, -2, -3, -4])

In [44]:
d = torch.tensor( [1.2,2.5,3.5,4.5] )

In [45]:
torch.round(d)

tensor([1., 2., 4., 4.])

In [46]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [47]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [48]:
d = torch.tensor( [100,200,300,400] )

In [49]:
torch.clamp(d, min = 1, max = 2)

tensor([2, 2, 2, 2])

Reduction Operation

In [50]:
e = torch.randint( size = (2,3), low = 0, high = 10, dtype = torch.float32)

In [51]:
e

tensor([[0., 1., 9.],
        [9., 8., 0.]])

In [52]:
torch.sum(e)

tensor(27.)

In [53]:
torch.sum( e, dim=0 )

tensor([9., 9., 9.])

In [54]:
torch.sum( e, dim = 1)

tensor([10., 17.])

In [55]:
torch.mean(e)

tensor(4.5000)

In [56]:
torch.mean(e, dim = 0)

tensor([4.5000, 4.5000, 4.5000])

In [57]:
torch.median(e)

tensor(1.)

In [58]:
#max and min
torch.max(e)

tensor(9.)

In [59]:
torch.min(e)

tensor(0.)

In [60]:
torch.prod( e )

tensor(0.)

In [61]:
torch.std( e )

tensor(4.5935)

In [62]:
torch.var( e )

tensor(21.1000)

In [63]:
#argmin, argmax

torch.argmax(e)

tensor(2)

In [64]:
torch.argmin(e)

tensor(0)

Matrix operations

In [65]:
f = torch.randint( size = (2,3), low = 0, high = 10)
g = torch.randint( size = (3,2), low = 0, high = 10)

In [66]:
f

tensor([[7, 0, 0],
        [9, 5, 7]])

In [67]:
g

tensor([[3, 9],
        [4, 0],
        [5, 7]])

In [68]:
torch.matmul(f,g)

tensor([[ 21,  63],
        [ 82, 130]])

In [69]:
#dot product
vector1 = torch.tensor( [1,2] )
vector2 = torch.tensor( [3,4] )

In [70]:
torch.dot(vector1, vector2)

tensor(11)

In [71]:
f

tensor([[7, 0, 0],
        [9, 5, 7]])

In [72]:
f.shape

torch.Size([2, 3])

In [73]:
torch.transpose(f, 0, 1)

tensor([[7, 9],
        [0, 5],
        [0, 7]])

In [74]:
h = torch.randint(size=(3,3), low = 0, high = 10, dtype = torch.float32)

In [75]:
torch.det(h)

tensor(184.0000)

In [76]:
torch.inverse(h)

tensor([[-0.2500,  0.0978,  0.1957],
        [ 0.1250, -0.2011,  0.0978],
        [ 0.1250,  0.1467, -0.2065]])

Comparison Operations

In [77]:
i = torch.randint( size = (2,3), low = 0, high = 10)
j = torch.randint( size = (2,3), low = 0, high = 10)

In [78]:
i

tensor([[9, 2, 6],
        [7, 7, 8]])

In [79]:
j

tensor([[3, 6, 1],
        [5, 5, 0]])

In [80]:
# greater than
i > j

tensor([[ True, False,  True],
        [ True,  True,  True]])

In [81]:
# less than
i < j

tensor([[False,  True, False],
        [False, False, False]])

In [82]:
# equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [83]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

Special Function

In [84]:
k = torch.tensor( [0.001,20,30] )
k

tensor([1.0000e-03, 2.0000e+01, 3.0000e+01])

In [85]:
torch.log(k)

tensor([-6.9078,  2.9957,  3.4012])

In [86]:
# exp ( exponential - e power)

torch.exp(k)

tensor([1.0010e+00, 4.8517e+08, 1.0686e+13])

In [87]:
torch.sqrt(k)

tensor([0.0316, 4.4721, 5.4772])

In [88]:
#sigmoid
torch.sigmoid(k)

tensor([0.5002, 1.0000, 1.0000])

In [89]:
#softmax
# k_float = k.to(torch.float32)
#[Note: If int then have to convert to float]
torch.softmax(k, dim = 0)

tensor([9.3666e-14, 4.5398e-05, 9.9995e-01])

In [90]:
torch.relu(k)

tensor([1.0000e-03, 2.0000e+01, 3.0000e+01])

Inplace operations

In [91]:
a = torch.tensor( [1, 2, 3] )
a

tensor([1, 2, 3])

In [92]:
b = a + 5
b

tensor([6, 7, 8])

In [93]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [94]:
m

tensor([[0.9233, 0.9178, 0.7590],
        [0.7775, 0.6179, 0.3379]])

In [95]:
n

tensor([[0.2170, 0.9454, 0.7116],
        [0.1157, 0.6574, 0.3451]])

In [96]:
m.add_(n)

tensor([[1.1403, 1.8632, 1.4706],
        [0.8933, 1.2752, 0.6830]])

In [97]:
torch.relu_(m)

tensor([[1.1403, 1.8632, 1.4706],
        [0.8933, 1.2752, 0.6830]])

In [98]:
m.relu_()

tensor([[1.1403, 1.8632, 1.4706],
        [0.8933, 1.2752, 0.6830]])

Copying a tensor ( Deep copy and Shallow copy )

In [99]:
a = torch.tensor([1,2,3,4,5])
a

tensor([1, 2, 3, 4, 5])

In [100]:
b = a

In [101]:
b[2] = 30

In [102]:
b

tensor([ 1,  2, 30,  4,  5])

In [103]:
a

tensor([ 1,  2, 30,  4,  5])

In [104]:
b = a.clone()

In [105]:
b

tensor([ 1,  2, 30,  4,  5])

In [106]:
id(a)

137151269808368